CREATE TABLE [dbo].[Order]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Date] DATE NOT NULL,
	[CartId] INT NOT NULL FOREIGN KEY REFERENCES Cart(UserId),
	[TotalAmount] MONEY NOT NULL,
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES [User](Id)

)
