CREATE TABLE [dbo].[Order]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[CreatedDate] DATETIME NOT NULL,
	[TotalAmount] MONEY NOT NULL,
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES [User](Id),
	[PaymentId] INT NOT NULL FOREIGN KEY REFERENCES[Payment](Id)

)
