CREATE PROCEDURE [dbo].[spUsuario_Insert]
	@NOME VARCHAR(20),
	@IDADE INT,
	@EMAIL VARCHAR(50),
	@CPF VARCHAR(11),
	@ENDERECO VARCHAR(50),
	@Password nvarchar(50)

AS
BEGIN
	SET NOCOUNT ON
	DECLARE @Salt UNIQUEIDENTIFIER=NEWID()

	INSERT INTO dbo.Usuario (Nome, Idade, Email, Cpf, Endereco, [Password], Salt)
	VALUES (@NOME, @IDADE, @EMAIL, @CPF, @ENDERECO,HASHBYTES('SHA2_512', @Password+CAST(@Salt as NVARCHAR(36))), @Salt)
END
